version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: rwp_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  jobadder-mock:
    image: wiremock/wiremock:2.32.0
    ports:
      - "8080:8080"
    volumes:
      - ./integration-tests/mocks/jobadder:/home/wiremock
    command:
      - --verbose
      - --global-response-templating

  events-service:
    build:
      context: ./rwp-events
      dockerfile: Dockerfile.test
    environment:
      NODE_ENV: test
      DATABASE_URI: postgresql://postgres:postgres@postgres:5432/rwp_test
      REDIS_URI: redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  analytics-service:
    build:
      context: ./rwp-analytics
      dockerfile: Dockerfile.test
    environment:
      NODE_ENV: test
      DATABASE_URI: postgresql://postgres:postgres@postgres:5432/rwp_test
      REDIS_URI: redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      events-service:
        condition: service_started

volumes:
  postgres_data: